# Generated by Django 3.0.6 on 2020-07-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200709_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_writing',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
